---
title: "FY19_Search_October2018"
author: "Office of Marketing and Brand Management"
date: "Updated on `r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```


```{r}
library(dplyr)
library(knitr)
```




```{r}
LeadsUploaded <- read.csv("C:/Users/christine.iyer/Box/Search/FY19_Search/Search_October2018/FY19_Search_October2018.csv", header = T, stringsAsFactors = F)

LeadsUploaded <- LeadsUploaded %>%  mutate(
  Vendor = ifelse(grepl('^N', Recruiting.Category), 'NRCCUA', 'College Board'),
   Class = ifelse(grepl('SR', Recruiting.Category), 'Senior', 'Junior') ,
    Geo = ifelse(grepl('O', Recruiting.Category), 'Out-of-State', 'In-State'))
Leads <- LeadsUploaded %>% group_by(Vendor, Geo) %>% summarise(Leads = n())
```

```{r}
Inquiries <- LeadsUploaded %>% filter(Student.Stage != "Lead")

```



```{r}

ConfirmedWords <- c("Confirmed", "Withdrawn (After Confirmed)")
AdmittedWords <- c("Withdrawn (After Admitted)", "Admitted (Not Confirmed)" )

Inquiries <- Inquiries %>% 
mutate(ApplicationStatus =
  ifelse(App.Application.Status %in% AdmittedWords, "Admitted",
         ifelse(App.Application.Status %in% ConfirmedWords, "Confirmed",
                ifelse(App.Application.Status == "Enrolled", "Enrolled",
                       ifelse(App.Application.Status == "", "Inquiry", "Applied")))))

#trythis
# Don't forget to change the date!

# write.csv(Inquiries,"C:/Users/christine.iyer/Box/Search/FY18_Search/Search_Oct_2017/Conversions_October2017_4-6-20.csv", row.names = F)

```



```{r}

Inquiries1 <- Inquiries %>% group_by(Vendor,  Geo, Student.Stage, ApplicationStatus) %>% summarise(Inquiries = n())
# Final number inquiries
Inquiries2 <- Inquiries1 %>% group_by(Vendor,  Geo) %>% summarise(Inquiries = sum(Inquiries))



Applicants <- Inquiries1 %>% 
  filter(ApplicationStatus!= "Inquiry") %>% 
  group_by(Vendor, Geo,  ApplicationStatus) %>% 
  summarise(Apps = sum(Inquiries)) 
#Final number Applicants

Applicants1 <- Applicants %>% 
  group_by(Vendor,  Geo) %>% 
  summarise(Applicants = sum(Apps))
# Applicants1[8,1] <- "NRCCUA"
# Applicants1[8,2] <- "Senior"
# Applicants1[8,3] <- "Out-of_State"
# Applicants1[8,4] <- 0

```

```{r}

Admits <- Applicants %>% 
  filter(ApplicationStatus != "Applied") %>% 
  group_by(Vendor,  Geo, ApplicationStatus) %>% 
  summarise(Admits = sum(Apps))

#FOr number of Admits

Admits1 <- Admits %>% 
  group_by(Vendor,  Geo) %>% 
  summarise(Admits = sum(Admits))

# Admits1[8,1] <- "NRCCUA"
# Admits1[8,2] <- "Senior"
# Admits1[8,3] <- "Out-of_State"
# Admits1[8,4] <- 0

```


```{r}

Confirms <- Admits %>% 
  filter(ApplicationStatus != "Admitted") %>% 
  group_by(Vendor,  Geo, ApplicationStatus) %>% 
  summarise(Confirms = sum(Admits))

#FOr number of Admits

Confirms1 <- Confirms %>% 
  group_by(Vendor,  Geo) %>% 
  summarise(Confirms = sum(Confirms))
# Confirms1[8,1] <- "NRCCUA"
# Confirms1[8,2] <- "Senior"
# Confirms1[8,3] <- "Out-of_State"
# Confirms1[8,4] <- 0

```

```{r}
#FOr number of Enrolls

Enrolls <- Confirms %>% 
  filter(ApplicationStatus == "Enrolled") %>% 
  group_by(Vendor,  Geo) %>% 
  summarise(Enrolls = sum(Confirms))

# Enrolls[8,1] <- "NRCCUA"
# Enrolls[8,2] <- "Senior"
# Enrolls[8,3] <- "Out-of_State"
# Enrolls[8,4] <- 0

```

```{r}
Funnel <- cbind.data.frame(Leads, Inquiries2, Applicants1, Admits1, Confirms1, Enrolls)
```




```{r}

Funnel <- Funnel[, c(1:3, 6,9, 12, 15, 18)]
```






```{r}

nwew <- Funnel %>% 
  mutate(Inquiry_Yield = 
          paste0(round(Inquiries/Leads * 100,2), "%"),
         App_Yield = 
          paste0(round(Applicants/Leads * 100,2), "%"), 
         Leads = prettyNum(Leads, big.mark = ",")) %>% 
  select(Vendor,  Geo, Leads, Inquiries, Applicants, Admits, Confirms, Enrolls, Inquiry_Yield, App_Yield)


        
```




**In-State Senior**

```{r}
kable(nwew %>% filter(Geo == "In-State")%>% 
        select(Vendor, Leads:App_Yield)) 
```

**Out-of-State Senior **

```{r}
kable(nwew %>% filter(Geo == "Out-of-State")%>% 
        select(Vendor, Leads:App_Yield)) 
```

